### ISSUE TITLE
接收数据沾包问题

### ISSUE THREAD

**Issue by jinleil** [xiaoxinpro/SerialPortHelper#1]
请问在短时间内接收的多条数据，有拆包处理吗？我写的串口经常会有多条数据连在一起的情况。

**Comment by xiaoxinpro** [comment]
你说的这个是Windows底层的问题，这个连包的情况与波特率与你的CPU占用情况有关。

举个例子：9600波特率下间隔20ms左右发送一个包几乎都会连上的（前提是CPU无明显占用）

解决办法：
1. 增加串口波特率
2. 增加数据包之间的间隔
3. 自定义串口协议，软件上做包分割处理
