### ISSUE TITLE
 关闭串口时，偶尔会让界面死锁，SerialReceviedTimeInterval越低概率越高

### ISSUE THREAD

**Issue by maoxiao181018** [xiaoxinpro/SerialPortHelper#3]
把SerialReceviedTimeInterval调成1，按几下就会卡死，10的时候就是偶然出现一次。
参考此文章，添加两个bool变量解决。https://www.cnblogs.com/feifeivictor/p/4240669.html
经短暂测试，未发现其他影响。

**Comment by xiaoxinpro** [comment]
你反馈的问题我没有成功复现，以下是我测试结果：（串口收发短接，测试30分钟没有出现异常）

![image](https://user-images.githubusercontent.com/11443745/86918004-9f2c8800-c158-11ea-9998-6612297b90c4.png)

你看一下是不是我测试的方法有问题，麻烦再把问题描述的清楚些。

**Comment by maoxiao181018** [comment]
可能是我的收发频率比较高？我的波特率是115200，大概是100ms一次，一次896个字节，我发个视频给你看吧。
字节数比较小或者发送频率比较低的情况下，狂点开关串口也会出现卡死，但一般不会遇到这种情况吧。
https://pan.baidu.com/s/1gla_DIgp2Bg2RFb9NAcaHg
ozma

**Comment by maoxiao181018** [comment]
9600波特率的设备，我手里暂时没有。如果你手上没有115200的设备的话，试试狂点看能不能复现？

**Comment by xiaoxinpro** [comment]
我依旧没有复现你的问题，测试视频看下面的链接。

链接: https://pan.baidu.com/s/1l1W_Z5yeRahxakAk-oQk5A 提取码: 6i71

如果你可以修复问题可以fork代码进行修改再pull request

Thanks.
